version: '3'

services:

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  mysqldb:
    container_name: mysqldb-docker
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=weather
