version: '3'

services:

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  dynamodb-local:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"
    command: -jar DynamoDBLocal.jar -sharedDb

  awscli:
    image: amazon/aws-cli
    container_name: aws-cli
    volumes:
      - ./aws:/root/.aws
    depends_on:
      - dynamodb-local
    command: dynamodb --endpoint-url http://dynamodb-local:8000 create-table --table-name city-weather-info --attribute-definitions AttributeName=city,AttributeType=S --key-schema AttributeName=city,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
