version: '3'

services:

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=weather
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
