spring:
  liquibase:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}
    user: ${database.username}
    password: ${database.password}

cache:
  host: localhost
  port: 6379

database:
  name: weather
  host: localhost
  port: 3306
  username: root
  password: password