spring:
  profiles:
    active: local

  redis:
    host: ${cache.host}
    port: ${cache.port}
    timeout: 5000

cache:
  host: ${CACHE_HOST}
  port: ${CACHE_PORT}

database:
  name: weather
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

application:
  cache:
    time-to-live: 3

  weather-stack:
    api: http://api.weatherstack.com/

  open-weather-map:
    api: http://api.openweathermap.org/data/2.5/

weather-stack-access-key: xxx
open-weather-map-access-key: xxx

logging:
  level:
    org.springframework.data.r2dbc: debug