spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
    timeout: 5000

application:
  cache:
    time-to-live: 3

  dynamo:
    region: "ap-east-1"
    endpoint: "http://localhost:8042"
    table: "city-weather-info"

  weather-stack:
    api: http://api.weatherstack.com/

  open-weather-map:
    api: http://api.openweathermap.org/data/2.5/

weather-stack-access-key: xxx
open-weather-map-access-key: xxx

